#pragma config(StandardModel, "RVW Fantasticbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
resetMotorEncoder(rearLeftMotor);
resetMotorEncoder(rearRightMotor);
resetMotorEncoder(frontRightMotor);
resetMotorEncoder(frontLeftMotor);

setMotorTarget(rearLeftMotor, 60, 80, false);
setMotorTarget(rearRightMotor, 60, 80, false);
setMotorTarget(frontLeftMotor, 600, 80, false);
setMotorTarget(frontRightMotor, 600, 80, false);

bool targetIsCompleted = (getMotorTargetCompleted(rearLeftMotor)
											 && getMotorTargetCompleted(rearRightMotor)
											 && getMotorTargetCompleted(frontLeftMotor)
											 && getMotorTargetCompleted(frontRightMotor));
while (!targetIsCompleted)
{
	motor[rearLeftMotor] = 80;
	motor[rearRightMotor] = 80;
	motor[frontLeftMotor] = 80;
	motor[frontRightMotor] = 80;

	getMotorEncoder(rearLeftMotor);
	getMotorEncoder(rearRightMotor);
	getMotorEncoder(frontLeftMotor);
	getMotorEncoder(frontRightMotor);
}

	motor[rearLeftMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;

}
