#pragma config(StandardModel, "RVW Fantasticbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define AUTONSPEED 100
#define MAXSPEED 127
task main()
{
	//Raise Arm
	motor[armMotor] = AUTONSPEED;
	motor[rightExtendMotor] = AUTONSPEED;
	motor[leftExtendMotor] = AUTONSPEED;
	wait1Msec(1000);
	motor[armMotor] = 0;
	motor[rightExtendMotor] = 0;
	motor[leftExtendMotor] = 0;
	//Move Forward
		//motor[frontLeftMotor] = AUTONSPEED;
		//motor[rearLeftMotor] = AUTONSPEED;
 	//	motor[frontRightMotor] = AUTONSPEED;
		//motor[rearRightMotor] = AUTONSPEED;
		//wait1Msec(400);
		//motor[frontLeftMotor] = 0;
		//motor[rearLeftMotor] = 0;
 	//	motor[frontRightMotor] = 0;
		//motor[rearRightMotor] = 0;
		//wait1Msec(3000);
		//Turn Left
		motor[frontRightMotor] = AUTONSPEED-30;
		motor[rearRightMotor] = AUTONSPEED-30;
		wait1Msec(980);
		motor[frontLeftMotor] = 0;
		motor[rearLeftMotor] = 0;
 		motor[frontRightMotor] = 0;
		motor[rearRightMotor] = 0;
		wait1Msec(1000);

		//Move forward to mobile goal
		motor[frontLeftMotor] = MAXSPEED;
		motor[rearLeftMotor] = MAXSPEED;
 		motor[frontRightMotor] = MAXSPEED;
		motor[rearRightMotor] = MAXSPEED;
		wait1Msec(2180);
		motor[frontLeftMotor] = 0;
		motor[rearLeftMotor] = 0;
 		motor[frontRightMotor] = 0;
		motor[rearRightMotor] = 0;
		wait1Msec(500);

		////Turn right
		motor[frontLeftMotor] = MAXSPEED;
		motor[rearLeftMotor] = MAXSPEED;
		motor[frontRightMotor] = 0;
		motor[rearRightMotor] = 0;
		wait1Msec(1000);
		motor[frontLeftMotor] = 0;
		motor[rearLeftMotor] = 0;
 		motor[frontRightMotor] = 0;
		motor[rearRightMotor] = 0;
		wait1Msec(1000);

		//Move backward
		motor[frontLeftMotor] = -MAXSPEED+20;
		motor[rearLeftMotor] = -MAXSPEED+20;
		motor[frontRightMotor] = -20;
		motor[rearRightMotor] = -20;
		wait1Msec(1500);
		motor[frontLeftMotor] = 0;
		motor[rearLeftMotor] = 0;
 		motor[frontRightMotor] = 0;
		motor[rearRightMotor] = 0;
		wait1Msec(1000);

		//move forward
		motor[frontLeftMotor] = MAXSPEED/4-10;
		motor[rearLeftMotor] = MAXSPEED/4-10;
		motor[frontRightMotor] = MAXSPEED;
		motor[rearRightMotor] = MAXSPEED;
		wait1Msec(1000);
		motor[frontLeftMotor] = 0;
		motor[rearLeftMotor] = 0;
 		motor[frontRightMotor] = 0;
		motor[rearRightMotor] = 0;
		wait1Msec(1000);
		////arm down
	motor[armMotor] = -80;
	motor[rightExtendMotor] = -80;
	motor[leftExtendMotor] = -80;
	wait1Msec(1000);
	motor[armMotor] = 0;
	motor[rightExtendMotor] = 0;
	motor[leftExtendMotor] = 0;

		////Open claw
		motor[clawMotor] = 50;
		wait1Msec(3000);
		motor[clawMotor] = 0;
		wait1Msec(500);

		//Back up to the white line

		motor[frontLeftMotor] = -MAXSPEED/4;
		motor[rearLeftMotor] = -MAXSPEED/4;
 		motor[frontRightMotor] = -MAXSPEED/4;
		motor[rearRightMotor] = -MAXSPEED/4;
		wait1Msec(2200);
		motor[frontLeftMotor] = 0;
		motor[rearLeftMotor] = 0;
 		motor[frontRightMotor] = 0;
		motor[rearRightMotor] = 0;
		wait1Msec(500);

		//Turn Around
		//Go Forward into the goal
		//Drop mobile goal and cone

}
