#pragma config(StandardModel, "RVW Fantasticbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void StopAll()
{
	motor[rearRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;
}

task main()
{
	while(SensorValue[middleLight] < 1491){
		motor[rearRightMotor] = 60;
motor[rearLeftMotor] = 60;
motor[frontLeftMotor] = 60;
motor[frontRightMotor] = 60;

	}
StopAll();


}
