#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LeftLightSensor, sensorReflection)
#pragma config(Sensor, in2,    MiddleLightSensor, sensorReflection)
#pragma config(Sensor, in3,    RightLightSensor, sensorReflection)
#pragma config(Sensor, in4,    WristPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in6,    GyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl7,  TouchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  SonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  RightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LeftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ArmEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  LeftExtensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  WristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           FrontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RearRightMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RearLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ClawMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          WristMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RVWFantasticBotSensorFunctions.c"
#include "RVWFantasticBotMiscFunctions.c"
//Include files containing functions including movement functions

task main()
{
	init();
	while(true)
	{
		loopCode();
		switch(step)
		{
		case 0: //Move to the mobile goal and lift arm
			setArmTo(60);
			if(goForward(1200, 750, false) == 0)
					clearStep();
				break;
			case 1: //Release cone onto the mobile goal (2 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 2: //Lower the arm and wrist
				setArmTo(-10);
				setWristTo(1404);
				if(wait(350) == 0)
					clearStep();
				break;
			case 3: //Grab the mobile goal
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 4: //Turn to face the matchloads
				if(turn(2561) == 0)
					clearStep();
				break;
			case 5: //Move toward the matchload
				if(goForward(850) == 0)
					clearStep();
				break;
			case 6: //Tilt wrist up to stack another cone (4 points)
				if(setWristTo(1600) == 0)
					clearStep();
				break;
			case 7: //Move back and move wrist down
				setWristTo(1404);
				if(goForward(-280) == 0)
					clearStep();
				break;
			case 8: //Turn towards the wall
				if(turn(2250) == 0)
					clearStep();
				break;
			case 9: //Move forward a small amount
				if(goForward(100, 1000) == 0)
					clearStep();
				break;
			case 10: //Let go of the mobile goal
				openClaw(127);
				if(wait(100) == 0)
					clearStep();
				break;
			case 11: //Move back
				if(goForward(-130, 800) == 0)
					clearStep();
				break;
			case 12: //Turn to face a cone
				if(turn(3150) == 0)
					clearStep();
				break;
			case 13: //Move to the cone
				if(goForward(400) == 0)
					clearStep();
				break;
			case 14: //Close the claw to grab the cone
				openClaw(-127);
				if(wait(100) == 0)
					clearStep();
				break;
			case 15: //Lift up arm and lower wrist
				setWristTo(333);
				if(setArmTo(325) == 0)
					clearStep();
				break;
			case 16: //Move forward
				if(goForward(275) == 0)
					clearStep();
				break;
			case 17: //Turn to between the mobile goal and the preloads
				if(turn(1880) == 0)
					clearStep();
				break;
			case 18: //Move forward
				if(goForward(300) == 0)
					clearStep();
				break;
			case 19: //Turn to place third cone
				if(turn(1680) == 0)
					clearStep();
				break;
			case 20: //Release cone to score it (6 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 21: //Turn to preloads
				if(turn(2200, 14400) == 0)
					clearStep();
				break;
			case 22: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 23: //Turn to place fourth cone
				if(turn(1700, 14400) == 0)
					clearStep();
				break;
			case 24: //Release cone to score it (8 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 25: //Turn to preloads
				if(turn(2200, 14400) == 0)
					clearStep();
				break;
			case 26: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 27: //Turn to place fifth cone
				setArmTo(350);
				if(turn(1720, 14400) == 0)
					clearStep();
				break;
			case 28: //Release cone to score it (10 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 29: //Turn to preloads
				setArmTo(320);
				if(turn(2240, 14400) == 0)
					clearStep();
				break;
			case 30: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 31: //Turn to place sixth cone
				setArmTo(400);
				extendArmTo(181);
				if(turn(1740, 14400) == 0)
					clearStep();
				break;
			case 32: //Release cone to score it (12 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 33: //Turn to preloads
				setArmTo(320);
				extendArmTo(0);
				if(turn(2240, 14400) == 0)
					clearStep();
				break;
			case 34: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 35: //Turn to place seventh cone
				setArmTo(425);
				extendArmTo(233);
				if(turn(1790, 14400) == 0)
					clearStep();
				break;
			case 36: //Release cone to score it (14 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 37: //Move arm down to pick up mobile goal
				setWristTo(1404);
				extendArmTo(0);
				if(setArmTo(-10) == 0)
					clearStep();
				break;
			case 38: //Move forward towards mobile goal
				if(goForward(150) == 0)
					clearStep();
				break;
			case 39: //Grab mobile goal
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 40: //Turn to begin navigating to the blue zone
				if(turn(450, 1800, -1) == 0)
					clearStep();
				break;
			case 41: //Lift arm and lower the wrist
				setWristTo(685);
				if(setArmTo(240) == 0)
					clearStep();
				break;
			case 42: //Move forward
				if(goForward(520) == 0)
					clearStep();
				break;
			case 43: //Turn
				if(turn(3180) == 0)
					clearStep();
				break;
			case 44: //Move forward some more
				if(goForward(800) == 0)
					clearStep();
				break;
			case 45: //Turn
				if(turn(410) == 0)
					clearStep();
				break;
			case 46: //Move forward to the blue zone
				if(goForward(2400) == 0)
					clearStep();
				break;
			case 47: //Turn to face the blue zone
				if(turn(0) == 0)
					clearStep();
				break;
			case 48: //Move up to the blue zone bar
				if(abs(goForward(42, 250, true)) <= 16)
					clearStep();
				break;
			case 49: //Extend the arm
				if(extendArmTo(855) == 0)
					clearStep();
				break;
			case 50: //Open the claw and release the mobile goal (34 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 51: //Un-extend the arm
				if(extendArmTo(0) == 0)
					clearStep();
				break;
		}
	}
}
