#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LeftLightSensor, sensorReflection)
#pragma config(Sensor, in2,    MiddleLightSensor, sensorReflection)
#pragma config(Sensor, in3,    RightLightSensor, sensorReflection)
#pragma config(Sensor, in4,    WristPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in6,    GyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl7,  TouchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  SonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  RightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LeftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ArmEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  LeftExtensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  WristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           FrontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RearRightMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RearLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ClawMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          WristMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Run with fantastic bot on the red tile closest to the preloads

#include "RVWFantasticBotSensorFunctions.c"
#include "RVWFantasticBotMiscFunctions.c"
//Include files containing functions including movement functions

task main()
{
	init();
	while(true)
	{
		loopCode();
		switch(step)
		{
			case 0: //Move to the mobile goal and lift arm
				setArmTo(60);
				if(goForward(1200, 750, false) == 0)
					clearStep();
				break;
			case 1: //Release cone onto the mobile goal (2 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 2: //Lower the arm and wrist
				setArmTo(-10);
				setWristTo(1404);
				if(wait(350) == 0)
					clearStep();
				break;
			case 3: //Grab the mobile goal
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 4: //Turn to face the matchloads
				if(turn(2561) == 0)
					clearStep();
				break;
			case 5: //Move toward the matchload
				if(goForward(570) == 0)
					clearStep();
				break;
			case 6:
				//if(setWristTo(1600) == 0)
					clearStep();
				break;
			case 7: //Move back and move wrist down
				//setWristTo(1404);
				//if(goForward(-280) == 0)
					clearStep();
				break;
			case 8: //Turn towards the wall
				if(turn(2173) == 0)
					clearStep();
				break;
			case 9: //Move forward a small amount
				if(goForward(100, 1000) == 0)
					clearStep();
				break;
			case 10: //Let go of the mobile goal
				openClaw(127);
				if(wait(100) == 0)
					clearStep();
				break;
			case 11: //Move back
				if(goForward(-130, 800) == 0)
					clearStep();
				break;
			case 12: //Turn to face a cone
				if(turn(3150) == 0)
					clearStep();
				break;
			case 13: //Move to the cone
				if(goForward(400) == 0)
					clearStep();
				break;
			case 14: //Close the claw to grab the cone
				openClaw(-127);
				if(wait(100) == 0)
					clearStep();
				break;
			case 15: //Lift up arm and lower wrist
				setWristTo(333);
				if(setArmTo(325) == 0)
					clearStep();
				break;
			case 16: //Move forward
				if(goForward(275) == 0)
					clearStep();
				break;
			case 17: //Turn to between the mobile goal and the preloads
				if(turn(1880) == 0)
					clearStep();
				break;
			case 18: //Move forward
				if(goForward(300) == 0)
					clearStep();
				break;
			case 19: //Turn to place second cone
				extendArmTo(200);
				if(turn(1610) == 0)
					clearStep();
				break;
			case 20: //Release cone to score it (4 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 21: //Turn to preloads
				extendArmTo(0);
				if(turn(2200, 14400) == 0)
					clearStep();
				break;
			case 22: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 23: //Turn to place third cone
				extendArmTo(200);
				if(turn(1620, 14400) == 0)
					clearStep();
				break;
			case 24: //Release cone to score it (6 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 25: //Turn to preloads
				extendArmTo(0);
				if(turn(2200, 14400) == 0)
					clearStep();
				break;
			case 26: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 27: //Turn to place fourth cone
				extendArmTo(200);
				setArmTo(350);
				if(turn(1660, 14400) == 0)
					clearStep();
				break;
			case 28: //Release cone to score it (8 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 29: //Turn to preloads
				extendArmTo(0);
				setArmTo(320);
				if(turn(2240, 14400) == 0)
					clearStep();
				break;
			case 30: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 31: //Turn to place fifth cone
				setArmTo(400);
				extendArmTo(281);
				if(turn(1680, 14400) == 0)
					clearStep();
				break;
			case 32: //Release cone to score it (10 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 33: //Turn to preloads
				setArmTo(320);
				extendArmTo(0);
				if(turn(2240, 14400) == 0)
					clearStep();
				break;
			case 34: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 35: //Turn to place sixth cone
				setArmTo(425);
				extendArmTo(333);
				if(turn(1750, 14400) == 0)
					clearStep();
				break;
			case 36: //Release cone to score it (12 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 37: //Turn to preloads
				setArmTo(320);
				extendArmTo(0);
				if(turn(2240, 14400) == 0)
					clearStep();
				break;
			case 38: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 39: //Turn to place seventh cone
				setArmTo(450);
				extendArmTo(400);
				if(turn(1770, 14400) == 0)
					clearStep();
				break;
			case 40: //Release cone to score it (14 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 41: //Turn to preloads
				setArmTo(320);
				extendArmTo(0);
				if(turn(2240, 14400) == 0)
					clearStep();
				break;
			case 42: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 43: //Turn to place eighth cone
				setArmTo(464);
				turn(1800, 14400);
				if(extendArmTo(483) == 0)
					clearStep();
				break;
			case 44: //Release cone to score it (16 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 45: //Turn to preloads
				setArmTo(320);
				turn(2300, 14400);
				if(extendArmTo(0) == 0)
					clearStep();
				break;
			case 46: //Grab preload
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 47: //Turn to place ninth cone
				setArmTo(512);
				turn(1860, 14400);
				if(extendArmTo(900) == 0)
					clearStep();
				break;
			case 48: //Release cone to score it (18 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 49: //Turn to red mobile goal while extending and lowering arm.
				setWristTo(840);
				extendArmTo(642);
				setArmTo(130);
				if(turn(3000, 1800, -1) == 0)
					clearStep();
				break;
			case 50: //Grab mobile goal
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 51: //Turn away from the preloading zone and extend arm
				setArmTo(250);
				extendArmTo(900);
				if(turn(900, 1800, 1) == 0)
					clearStep();
				break;
			case 52: //Move forwards
				if(goForward(500) == 0)
					clearStep();
				break;
			case 53: //Move towards the starting tile
				if(turn(1350) == 0)
					clearStep();
				break;
			case 54: //Move towards the starting tile
				if(goForward(1400) == 0)
					clearStep();
				break;
			case 55: //Turn towards the 20 point zone
				if(turn(1800) == 0)
					clearStep();
				break;
			case 56: //Move towards the bar in front of the 10 point zone
				if(abs(goForward(41, 250, true)) <= 17)
					clearStep();
				break;
			case 57: //Drop the mobile goal into the 20 point zone (38 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 58:
				if(goForward(-100) == 0)
				{
					step++; //Case 59 was not working for some reason, and the only fix I could find was going straight to case 60
					clearStep();
				}
				break;
			case 60: //Turn to face directly away from the middle of the field
				if(turn(1600) == 0)
					clearStep();
				break;
			case 61: //Move backwards towards the middle of the field, lower arm, and un-extend arm
				extendArmTo(100);
				setArmTo(150);
				if(goForward(-1600) == 0)
					clearStep();
				break;
			case 62: //Turn towards the cone
				if(turn(500) == 0)
					clearStep();
				break;
			case 63: //Grab the cone
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 64: //Turn towards the mobile goal and raise arm
				setArmTo(250);
				if(turn(910) == 0)
					clearStep();
				break;
			case 65: //Move towards the mobile goal
				extendArmTo(0);
				if(goForward(630) == 0)
					clearStep();
				break;
			case 66: //Drop cone onto the mobile goal (40 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 67: //Turn towards a second cone and lower arm
				setArmTo(130);
				if(turn(435) == 0)
					clearStep();
				break;
			case 68: //Grab the cone
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 69: //Turn back to the mobile goal and raise arm
				setArmTo(250);
				if(turn(920) == 0)
					clearStep();
				break;
			case 70: //Drop cone onto the mobile goal (42 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 71: //Turn to a third cone, lower the arm, and extend the arm
				setArmTo(170);
				turn(3408);
				if(extendArmTo(900) == 0)
					clearStep();
				break;
			case 72: //Grab the cone
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 73: //Raise the arm, turn to the mobile goal, and un-extend the arm
				setArmTo(250);
				turn(950);
				if(extendArmTo(0) == 0)
					clearStep();
				break;
			case 74: //Drop cone onto the mobile goal (44 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 75: //Move forward slightly and lower arm
				goForward(100);
				if(setArmTo(100) == 0)
					clearStep();
				break;
			case 76: //Grab the mobile goal
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 77: //Turn to the corner of the field with the blue 20 point zone
				if(turn(3350) == 0)
					clearStep();
				break;
			case 78: //Move forward, pushing the red mobile goal out of the way
				if(goForward(1500) == 0)
					clearStep();
				break;
			case 79: //Turn towards the 20 point zone
				if(turn(200) == 0)
					clearStep();
				break;
			case 80: //Move towards the 20 point zone, extend the arm, and raise the arm
				setArmTo(175);
				extendArmTo(900);
				if(goForward(1200) == 0)
					clearStep();
				break;
			case 81: //Drop the mobile goal into the 20 point zone (64 points)
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
		/**/}
	}
}
