#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LeftLightSensor, sensorReflection)
#pragma config(Sensor, in2,    MiddleLightSensor, sensorReflection)
#pragma config(Sensor, in3,    RightLightSensor, sensorReflection)
#pragma config(Sensor, in4,    WristPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in6,    GyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl7,  TouchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  SonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  RightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LeftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ArmEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  LeftExtensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  WristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           FrontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RearRightMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RearLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ClawMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          WristMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RVWFantasticBotSensorFunctions.c"
#include "RVWFantasticBotMiscFunctions.c"
//Include files containing functions including movement functions

task main()
{
	init();
	while(true)
	{
		loopCode();
		switch(step)
		{
				case 0:
					if(goForward(200) == 0)
						clearStep();
					break;
				case 1:
					if(Arc(5, PI) == 0)
						clearStep();
					break;
			/*case 0:
				if(goForward(175) == 0)
					clearStep();
				break;
			case 1:
				if(turn(3125) == 0)
					clearStep();
				break;
			case 2:
				setWristTo(825);
				setArmTo(200);
				extendArmTo(100);
				if(goForward(1450) == 0)
					clearStep();
				break;
			case 3:
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 4:
				if(setArmTo(100) == 0)
					clearStep();
				break;
			case 5:
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 6:
				setArmTo(200);
				if(goForward(-1450) == 0)
					clearStep();
				break;
			case 7:
				if(turn(1550, 1800, 1) == 0)
					clearStep();
				break;
			case 8:
				goForward(120);
				if(extendArmTo(800) == 0)
					clearStep();
				break;
			case 9:
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 10:
				turn(900);
				if(extendArmTo(0) == 0)
					clearStep();
				break;
			case 11:
				if(goForward(1300) == 0)
					clearStep();
				break;
			case 12:
				if(turn(0) == 0)
					clearStep();
				break;
			case 13:
				if(goForward(870) == 0)
					clearStep();
				break;
			case 14:
				if(turn(450) == 0)
					clearStep();
				break;
			case 15:
				setArmTo(110);
				extendArmTo(180);
				if(goForward(1400) == 0)
					clearStep();
				break;
			case 16:
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 17:
				setArmTo(300);
				if(goForward(150) == 0)
					clearStep();
				break;
			case 18:
				openClaw(127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 19:
				if(setArmTo(100) == 0)
					clearStep();
				break;
			case 20:
				openClaw(-127);
				if(wait(50) == 0)
					clearStep();
				break;
			case 21:
				if(setArmTo(200) == 0)
					clearStep();
				break;
			case 22:
				if(goForward(-70) == 0)
					clearStep();
				break;
			case 23:
				if(turn(3150) == 0)
					clearStep();
				break;
			case 24:
				if(goForward(1500) == 0)
					clearStep();
				break;
/**/}
	}
}
